server:
  port: 9090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/doctor_hub
    username: afshin
    password: 1123581321

  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true



log:
  file:
    path: /home/afshinpy/doctor_hub/logs

doctorhub:
  auth:
    verificationCode:
      expireAfterMinute:3
      length:6


